### ISSUE TITLE
Change character class to dropdown and add same dropdown to monster sheet

### ISSUE THREAD

**Issue by Pusikas** [wesbaker/roll20-character-sheets#10]
Just a suggestion:

Currently, if you mistype a character's class, saving throws keep resetting to 0. So, like with monsters, it would probably be nice to have a character class dropdown, with an added "Normal Human" and "Custom" option for homebrew stuff. One of my players kept misspelling "Magic User" and got quite annoyed that his saves kept vanishing.

From #8:

> Entering the Saves by hand seems to work at first. When closing and re-opening the Centipede's sheet, the get resetted to 0, though.
> 
> UPDATE: The Saves keep resetting to 0, even when I enter a "1" as the HD.
> 
> UPDATE 3: When I to enter "Fighter" as a class on the character tab, then I get automagically filled Saves on the monster tab. This is kinda confusing. They ignore the monster's HD, tho.

**Comment by wesbaker** [comment]
Thinking about this further, I may as well keep this drop down the same between monster and character and make monster an option as well as custom.
