### ISSUE TITLE
some monster stats can't be easily entered in the sheet part 2

### ISSUE THREAD

**Issue by Pusikas** [wesbaker/roll20-character-sheets#11]
Some onsters have one attack mode that consists of multiple attacks, like this:
> Att 2 × claw (1d8), 1 × bite (2d6)

Some others can choose between multiple modes:
> Att 2 × claw (1d4) or 1 × thrown rock (1d6)

I am not sure how to best enter these in the sheet. I currently use the attack's description for this, but it's clumsy. I do not have any idea how to improve it, though.

Secondly, some monsters have multiple modes of movement and you can only enter the exploration speed. But that's no big deal, since stuff like Flying can easily be entered under "Abilities & Skills".

Lastly, the "NA" button for the number of monster appearing gives somewhat misleading results. First line is currently "Wandering". It should probably be "Wandering in dungeon". The second line is "Lair". And that probably means "Lair in dungeon". But the same number can be the number of monsters wandering in the wilderness. And a wilderness lair would be 5 times that, iirc. So maybe make it a tad more verbose and add a third line?

**Comment by Pusikas** [comment]
There's entries like this:
> NA 0 (1d4)

Which probably means that you can't find this kind of monster ins a dungeon at all. You meet 1d4 of them wandering the wilderness and 5 times that in their lair. I guess.

**Comment by wesbaker** [comment]
> I do not have any idea how to improve it, though.

So there _is_ a count column in Monster attacks, it's the column with the heading `#`. As for monsters with options, there's no good way to denote that, so I'll leave that to the GM for now.

> But that's no big deal, since stuff like Flying can easily be entered under "Abilities & Skills".

Agreed.

> And a wilderness lair would be 5 times that, iirc. So maybe make it a tad more verbose and add a third line?

Yeah, it sounds like I could have four rows really ([looking at the SRD](https://oldschoolessentials.necroticgnome.com/srd/index.php/General#Number_Appearing_.28NA.29)):

- Dungeon
  - Wandering monsters in a dungeon: first value
  - Monster lair in a dungeon: second value
- Wilderness
  - Wandering monsters in the wilderness: second value
  - Monster lair in the wilderness: second value * 5

**Comment by wesbaker** [comment]
<img width="256" alt="Screen Shot 2020-05-27 at 3 23 56 PM" src="https://user-images.githubusercontent.com/15715/83063414-1a652f00-a02e-11ea-910a-deca7bad49bf.png">

That's what I've got. Each roll is individual, but that's a limitation of Roll20. I'd like secondary headers, but this is the best option that fits for now.

**Comment by Pusikas** [comment]
And just one comment: both the character tab and the monster tab have a field "HD". The caption is the same. The fields' purpose is completely different. On the character tab you are supposed to enter the character's hit die. d4, d6 or d8. On the monster tab it's the monster's number of hit dice.

This got me confused at first. For some reason I was expecting fields with the same name to do the same. :)

**Comment by wesbaker** [comment]
For the character it was by necessity to allow for the different die sizes. For the GM, everything is a d8 as far as I could tell, so it was done out of simplicity. Am I wrong there? I don't mind changing it either to be the same on the monster sheet.

**Comment by Pusikas** [comment]
May I misinterpreted the fields. Pressing the "HD" on the character tab seems to roll the HD. I thought this was supposed to be used for a level up. On the monster tab, pressing the "HD" doesn't seem to do much. The number entered there is used to calculate the average HP. You can't enter stuff like "5d8" there. Only "5". That's what got me confused at first. The caption on the monster tab could maybe be "# of HD". But it's really no big deal.
