### ISSUE TITLE
Some things I'd like to see on the sheet (but are not very important)

### ISSUE THREAD

**Issue by Pusikas** [wesbaker/roll20-character-sheets#12]
My players started hiring retainers and torchbearers. That's when I noticed some things missing on the sheet:
- NPC reactions modifier and / or a button to make a monster reaction roll that's automagically modified by CHA
- Max number of retainers (some of my players are really overdoing it)
- Retainer Loyalty (I'd ask them to roll more often, if asking for my players' retainer loyalty wouldn't result in blank stares)

This stuff is coming up on a regular basis in my campaign now, so seeing this added to the sheet would be nice.

There is some more stuff missing, but most of it is not that important:
- Literacy & number of languages - you only have to look this up during character creation. Still, maybe text field to enter literacy and languages might be nice. Can just put it into the "Notes" field, so this is no big deal.
- Magic Saves - this comes up a lot more, and my players tend to forget to use their modifier, good or bad. I do not know if there is enough room for it, but maybe the "Spells, Rods, Staves"-Save could be split into "Spells" (modified by WIS) and "Rods & Staves" (not modified).

If you got nothing better to do at all, you could also make it an option to automatically set a player's speed based on their encumbrance and to set which encumbrance system to use. But that's probably not as useful as it sounds.

**Comment by wesbaker** [comment]
> * NPC reactions modifier and / or a button to make a monster reaction roll that's automagically modified by CHA

Totally doable. As for automatic, I have a few options there: ask for a modifier or use the currently selected token. If I go with the latter, it won't work for games that don't use tokens, so I lean toward asking for a modifier.

> * Max number of retainers (some of my players are really overdoing it)
> * Retainer Loyalty (I'd ask them to roll more often, if asking for my players' retainer loyalty wouldn't result in blank stares)

Hah. That's definitely doable. I'll need to think about where to put both of these.

> * Literacy & number of languages - you only have to look this up during character creation. Still, maybe text field to enter literacy and languages might be nice. Can just put it into the "Notes" field, so this is no big deal.

Yeah, I definitely lean towards leaving this as part of your notes for now. Some games use it heavily, others ignore it.

> * Magic Saves - this comes up a lot more, and my players tend to forget to use their modifier, good or bad. I do not know if there is enough room for it, but maybe the "Spells, Rods, Staves"-Save could be split into "Spells" (modified by WIS) and "Rods & Staves" (not modified).

Totally missed this one. Looking at [the rules it appears that it applies to everything _but_ breath weapons](https://oldschoolessentials.necroticgnome.com/srd/index.php/Ability_Scores#Wisdom_.28WIS.29):

> Magic saves: Is applied to saving throws (see Saving Throws) versus magical effects. This does not normally include saves against breath attacks, but may apply to any other saving throw category.

So it sounds like I need to modify everything but Breath Weapons. What's your take on that?

**Comment by Pusikas** [comment]
Well, guess so. Most staves sound like they're just creating spell effects, anyway. And I haven't found a rod with an effect you can save against.  Also, there's this from the rules:
> There are five saving throw categories: death (or poison), wands, paralysis (or petrification), breath attacks, spells (or magic rods or staves).

That sounds like rods and staves are to be saved against like spells, too.

Your quote also sounds like the WIS bonus may be applied to the other saves as well. So it may be better to list the bonus next to the save. Instead of modifying one save. Might come in handy when there is something like a death or petrification effect from a spell.

**Comment by Pusikas** [comment]
Found spells like "Death Spell" or "Flesh to Stone", that require a save vs death / petrification. But I guess the the WIS bonus would apply here. So it may really be better to list the modifier than to modify one save.

**Comment by wesbaker** [comment]
On Discord folks are saying it's always situational, so blanket applying it doesn't work. I thought about having it roll for two saving throws (one with and one without modifier), but that'd be two separate rolls, which is just weird.

I think ultimately there's two options:
- Have two buttons per saving throw, one with and one without modifier
- Have a checkbox (in the header maybe?) that applies the modifier while enabled

I think I lean towards the former, but I'll need to fiddle with how it looks.

<img width="341" alt="Screen Shot 2020-06-01 at 4 39 50 PM" src="https://user-images.githubusercontent.com/15715/83452339-8ed11100-a426-11ea-9f0c-e239a9d72fbc.png">

**Comment by Pusikas** [comment]
You could also add a 6th field in the row of saving throws and put the wisdom modifier there. Then at least players and the GM are less likely to forget it. Adding a cvheckbox might be overdoing it. It's probably enough to add a `@{modquery}` to the roll. Unlike attacks, saving throws are modified quite often.
