### ISSUE TITLE
Add a button for a reaction roll to the monster tab

### ISSUE THREAD

**Issue by wesbaker** [wesbaker/roll20-character-sheets#13]
From #12 

A morale roll already exists, but one for a reaction roll would be useful as well.

- It should be clickable
- It shouldn't show the result to the players

**Comment by Pusikas** [comment]
Wouldn't it be easier to add a button to the player's sheet? The modifier is just there and wouldn't have to be entered. Is it possible to create a button that sends a PM with the result to the GM?

**Comment by wesbaker** [comment]
I could add it to the player's sheet, but I _think_ the player can see the results. I'll have to test that out.

**Comment by wesbaker** [comment]
> I _think_ the player can see the results. I'll have to test that out.

Yep, the player can see the results of the reaction roll. I'll put it on the monster page and have the GM roll it.
