### ISSUE TITLE
saving-throws not saved

### ISSUE THREAD

**Issue by elbj** [wesbaker/roll20-character-sheets#16]
Hello

I have an issue. When I input any SavThr then close the sheet, they are not saved and their value is 0 when I open the sheet.

Regards

**Comment by elbj** [comment]
My bad ! I did not realise they where automaticaly calculated.

**Comment by elbj** [comment]
Sorry but there is really an issue with saving throws.
Create a monster, set HD, see the values are correct, close sheet, open sheet, they are all 0.

**Comment by wesbaker** [comment]
@elbj thanks for reporting this. I'll dig into it tomorrow morning.

**Comment by wesbaker** [comment]
@elbj just giving you a heads up that I _think_ I've found the issue, _but_ Roll20 is having all sorts of issues this morning with the Custom Sheet Sandbox which is making it hard to test. I'll see what I can do this weekend to get it fixed.

**Comment by wesbaker** [comment]
Alright I was able to test it just uploading the sheet into a custom game and it looks like it's fixed. I'm going to push it up now so it's ready to go Tuesday.

**Comment by elbj** [comment]
Great.

By the way, do you want French translations ?

**Comment by wesbaker** [comment]
> By the way, do you want French translations ?

If you're willing to make them, certainly!

**Comment by elbj** [comment]
Got it already. How can I give it to you ?

**Comment by wesbaker** [comment]
> Got it already. How can I give it to you ?

If you're comfortable with GitHub you can make a pull request. If not, you can either paste it in here or put it in [a gist](https://gist.github.com) and send me the link.

**Comment by elbj** [comment]
I'll try the pull request

**Comment by elbj** [comment]
No finally : https://gist.github.com/elbj/012db84c9286b15dc2dcbde6903830de
Is it ok ?

**Comment by wesbaker** [comment]
It looks good, but you're missing a few _that I just added_. Take a look at the latest that I have currently in pull request: https://github.com/wesbaker/roll20-character-sheets/blob/ose-1.3.0/Old%20School%20Essentials%20-%20AAC/translation.json. I think you're just missing these:

```json
  "reaction": "Reaction",
  "reaction-hostile": "Hostile, attacks",
  "reaction-unfriendly": "Unfriendly, may attack",
  "reaction-neutral": "Neutral, uncertain",
  "reaction-indifferent": "Indifferent, uninterested",
  "reaction-friendly": "Friendly, helpful",
  "charisma-modifier": "Charisma Modifier"
```

**Comment by elbj** [comment]
"reaction": "Réaction",
  "reaction-hostile": "Hostile, attaque",
  "reaction-unfriendly": "Inamical, peut attaquer",
  "reaction-neutral": "Neutre, incertain",
  "reaction-indifferent": "Indifférent, désintéressé",
  "reaction-friendly": "Amical, serviable",
  "charisma-modifier": "Modificateur de Charisme"

**Comment by wesbaker** [comment]
Done! Thanks for your contribution.

**Comment by elbj** [comment]
You're welcome
