### ISSUE TITLE
Add Dolmenwood classes to character sheet

### ISSUE THREAD

**Issue by wesbaker** [wesbaker/roll20-character-sheets#18]

**Comment by FrederickMuench** [comment]
Hi Wes,
i think that's an cool idea, but i think it could wait until Gavin organizes the Kickstarter or releases the Dolmen Wood Setting books.

**Comment by wesbaker** [comment]
Yeah, it’s a pretty low priority, _but_ they may come up in my game so I’ll probably add them and just change them later.
