### ISSUE TITLE
Rework Armour: 'AC' instead of 'AC Benefit'

### ISSUE THREAD

**Issue by FrederickMuench** [wesbaker/roll20-character-sheets#19]
A user has to fill in the 'AC Benefit' for an armour. It's not by the rules and can be very confusing for a user.
I think the armour's AC value should be filled in (e.g. Leather 7 or 12, Chainmail 5 or 14, etc.)

**Comment by wesbaker** [comment]
The reason for an AC Benefit is because it works for either AAC or DAC without the need to change it. I might be able to rework it though. Let me think about it.

**Comment by FrederickMuench** [comment]
Yeah, i totally understand why you made this :-)

But it's confusing for the user when the values are not the same as listed in the rules. I know, it makes things probably more complicated, but it's an important thing.

**Comment by wesbaker** [comment]
Alright I have it worked out, though it will require rejiggering your characters when the update hits, though any monsters created should be just fine as they don't wear armor.

**Comment by FrederickMuench** [comment]
God damit, Wes! You are a real work horse.
