### ISSUE TITLE
Rework damage calculation for attack rolls

### ISSUE THREAD

**Issue by FrederickMuench** [wesbaker/roll20-character-sheets#21]
Hovering over the calculated damage of an attack shows this:

<img width="245" alt="Bildschirmfoto 2020-07-02 um 11 36 57" src="https://user-images.githubusercontent.com/23061171/86342790-5f493a80-bc58-11ea-9c81-4f2f1acbb221.png">

It's not really clear to the user how that value was calculated and it's not really clear what that means.

I would expect something **like** for the attack roll
<img width="214" alt="Bildschirmfoto 2020-07-02 um 11 42 24" src="https://user-images.githubusercontent.com/23061171/86343382-2d84a380-bc59-11ea-84a2-acbfba9a3a12.png">

(Weapon damage die) + (STR / DEX modifer) + (Damage bonus from weapon)
example: "1d8 + 1 + 0 = (5) + 1 + 0"

**Comment by wesbaker** [comment]
It’s like this to ensure a minimum of one damage. If we don’t care about results of 0, then I can easily show the resulting die roll.

**Comment by FrederickMuench** [comment]
I can't find any rules that says it can't be '0'. I'd argue it's more important to make the calculation visible. Any GM can easily make a ruling on this and decide for him-/herself. It's the same on all sheet i know from other games.

**Comment by wesbaker** [comment]
I think it’s reasonable to show the full roll and let the GM decide. But for what it’s worth, here it is [in the rules](https://oldschoolessentials.necroticgnome.com/srd/index.php/Combat#Rolling_for_Damage):

> Minimum damage: An attack which hits always deals at least one point of damage, even when damage modifiers reduce the number rolled to 0 or less.
