### ISSUE TITLE
Add 'Critical' message to rolled attack

### ISSUE THREAD

**Issue by FrederickMuench** [wesbaker/roll20-character-sheets#22]
Without hovering over the the attack roll result, it is not clear whether a roll was an critical hit or miss.
A rolled '1' is always a Miss and a '20' is always a Hit independent of the targets AC.
I think it can be easily overseen, because you always see the end-result and not the dice-value.

I'd suggest a message like "Critical Hit!" or "Critical Miss!" that is visible in the table that shows the attack and damage roll results.

**Comment by wesbaker** [comment]
I'm a little hesitant here on the wording. So yes, a 1 always misses and a 20 always hits, and I can (and was...) show the roll as being green on the highest result of a die and red on the lowest result on the die. However, rules as written they aren't _critical_, they just always hit or always miss. Criticals are a commonly enough used house rule though. What do you think?

<img width="261" alt="Screen Shot 2020-07-02 at 11 18 31 AM" src="https://user-images.githubusercontent.com/15715/86376997-c6192480-bc55-11ea-9f2a-cc01457f9055.png">

**Comment by wesbaker** [comment]
<img width="263" alt="Screen Shot 2020-07-02 at 11 20 39 AM" src="https://user-images.githubusercontent.com/15715/86377240-11cbce00-bc56-11ea-93ca-c040f70d617d.png">
