### ISSUE TITLE
Add support link or email

### ISSUE THREAD

**Issue by FrederickMuench** [wesbaker/roll20-character-sheets#24]
We have an official email adress 'webdev@necroticgnome.com'.
The Idea is that people have the possibility to report bugs and express their opinion and experience on the Roll20-sheet.

Could you place that email somewhere on the sheet with a note, that its for reports, opions and questions in the relation to the sheet (and other digital stuff)?

**Comment by wesbaker** [comment]
What kind of note do you want? I want character sheet bug reports and suggestions to come here so we’re not playing a game of telephone.

**Comment by FrederickMuench** [comment]
I understand your point, but i think many people who use the sheets don't even know what github is. I think, the issues that show up here are only from people who have a bit more 'advanced technical knowledge'. 

My guess is, we loose all that potential feedback from the people who don't have a clue about github. But everyone knows what an email address is. 
About your worries: I check the email address regularly and can easily forward any emails to you. It's some work i'm willing to make.

Are you alright with that?

**Comment by wesbaker** [comment]
I’m happy having links to both and having people pick what they want. It’s not that I’m worried about you checking email, it’s that I don’t want additional layers between users of the sheet and me.

**Comment by FrederickMuench** [comment]
Links to both sounds good.

**Comment by wesbaker** [comment]
Sadly we cannot actually create links, but I'll just include the URL and the email address.

<img width="867" alt="Screen Shot 2020-07-02 at 3 41 18 PM" src="https://user-images.githubusercontent.com/15715/86402819-7a2ca680-bc7a-11ea-899a-8a9eb28711fc.png">
