### ISSUE TITLE
Update French Translations

### ISSUE THREAD

**Issue by wesbaker** [wesbaker/roll20-character-sheets#25]
@elbj I had to change some translation keys and add some new ones. Mind giving me the updated French translations? https://github.com/wesbaker/roll20-character-sheets/compare/master...wesbaker:ose-1.5.0#diff-8d55a3bc5035d816488bf296d4f38828

In particular:
- Added `"critical-hit": "Critical Hit!"`
- Added `"critical-miss": "Critical Miss!"`
- Added `"dolmenwood": "Dolmenwood"` (this shouldn't need one being a proper noun)
- Changed `"modifier": "Threshold modifier"` to `"modifier": "Situational Bonus"`
- Changed `"threshold-modifier-enabled": "Threshold Modifier Enabled?"` to `"situational-bonus-enabled": "Situational Bonus Enabled?"`

**Comment by elbj** [comment]
Sure I'd be pleased to help you translating it.

Critical Hit! => «Toucher critique» or «Coup critique»
Critical Miss! => «Maladresse» or «Échec critique»
As you said, Dolmenwood seems to be a proper noun
Situational Bonus => «Bonus de situation» or «Bonus de contexte» or just «Bonus»
Situational Bonus Enabled? => juste translate Enabled by «Actif»

**Comment by wesbaker** [comment]
@elbj Thank you so much! Mind double-checking my work in eee1ae2?

**Comment by wesbaker** [comment]
@elbj I think I got everything. Mind doing a final review? https://github.com/wesbaker/roll20-character-sheets/blob/ose-1.5.0/Old%20School%20Essentials%20-%20AAC/translations/fr.json

**Comment by elbj** [comment]
"find-secret-door-full": "Find secret door",
  "find-secret-room-full": "Trouver porte secrète",

witch one is the good one ?

**Comment by wesbaker** [comment]
@elbj I think `find-secret-room-full` is a leftover. I'll remove that. Only `find-secret-door-full` is needed.

**Comment by elbj** [comment]
So the translation : "Trouver porte secrète"

**Comment by wesbaker** [comment]
Got it. Should be all set then. Thank you again for your help.

**Comment by wesbaker** [comment]
@elbj I _just_ added four more that need translation, sorry about that 😢 

```json
  "about": "About",
  "about-description": "If you have any suggestions or problems with the character sheet, please reach out.",
  "submit-issue": "Submit a feature request or bug",
  "email-us": "Email us with comments or questions"
```

**Comment by elbj** [comment]
"About" => «À propos»
"If you have any suggestions or problems with the character sheet, please reach out." => «Si vous avex des suggestions ou des problèmes avec la feuille de personnage, merci de me contacter.»
"Submit a feature request or bug" => «Soumettre une nouvelle fonctionnalité ou un bug.»
"Email us with comments or questions" => «Envoyez nous vos commentaires ou questions par email.»

**Comment by wesbaker** [comment]
Thank you again!

**Comment by elbj** [comment]
Welcome
