### ISSUE TITLE
STR mod not appearing in melee attack dice.

### ISSUE THREAD

**Issue by Dextolen** [wesbaker/roll20-character-sheets#26]
Wonderful sheet!

**Comment by wesbaker** [comment]
@Dextolen If you were running a game before this week, you may need to go in and fiddle with the attack type (melee vs ranged) to get it to be set properly. Mind trying that first?

**Comment by wesbaker** [comment]
Oh, nope, I see it too now. Let me take a crack at it.

**Comment by wesbaker** [comment]
Alright, I _think_ I have a fix up for this. It should hit next week. In the mean time a workaround is to switch between melee and ranged and then back again.

**Comment by Dextolen** [comment]
I think it's fixed already!  I can't wait to convert my campaigns to this new sheet

**Comment by wesbaker** [comment]
@Dextolen I'm happy to hear it! Please let me know if you have any suggestions or other feedback as well. I'm currently running my group through The Hole in the Oak and looking for any quality of life improvements.
