### ISSUE TITLE
Spells per Level

### ISSUE THREAD

**Issue by Dextolen** [wesbaker/roll20-character-sheets#28]
Hi, if possible, a way to show spells cast/day per level.

**Comment by wesbaker** [comment]
Doing it per class would require a bit more work and some data entry, but in the meanwhile I could easily add some fields to count what you can cast and also add spell levels to the listings.

Would it be useful to have both what you can cast and either what you've already cast or what you can still cast before resting?

**Comment by Dextolen** [comment]
No need to actually track class data. just a place to store the number of spells we have per level, just above the spells section. with a text box for each level 1, 2, 3, 4, 5, 6.

**Comment by frankie-break-bone** [comment]
![image](https://user-images.githubusercontent.com/65683228/87845312-2afa8e80-c894-11ea-85e0-ec2c800b9fd2.png)
A more pragmatic version of this improvement would be super handy: Currently I'm putting the spell level in the name, and using the effect field to mark an X if the PC has it prepared. A bona-fide version of this would be lovely, eventually.

**Comment by wesbaker** [comment]
@frankie-break-bone I've added both a prepared checkbox and a spell level column.

**Comment by ReiMalebario** [comment]
Ideally, since it's possible to prepare the same spell multiple times, the prep box should be a number field rather than a check box.

**Comment by wesbaker** [comment]
@ReiMalebario that's a good point. I'll take a gander today.

**Comment by wesbaker** [comment]
Got it taken care of with 8600b45df
