### ISSUE TITLE
Calculate AC hit when using DAC

### ISSUE THREAD

**Issue by wesbaker** [wesbaker/roll20-character-sheets#29]
Show what AC you hit based on the roll you made when using DAC.

**Comment by Dextolen** [comment]
This is a wonderful idea.

**Comment by gavinnorman** [comment]
Note that there are actually _three_ means of resolving attack rolls in OSE:
1. AAC with an attack bonus.
2. THAC0.
3. The attack matrix.

3 is actually the default.

**Comment by wesbaker** [comment]
@gavinnorman my aim is to use the attack matrix since THAC0 is a shortcut over that. I probably miss worded this issue and it should be "Calculate AC Hit when using DAC"

**Comment by wesbaker** [comment]
I dug into this a bit today and ended up frustrated. I _can_ calculate the AC hit, but it has to be simple so I need to use THAC0 calculation and not the matrix. Further still because of the way I have to do the calculations I can no longer display "Natural 1" or "Natural 20" beneath the roll. That being said, the roll still appears as red (if it's a 1) or green (if it's a 20):

<img width="260" alt="Screen Shot 2020-07-14 at 2 12 24 PM" src="https://user-images.githubusercontent.com/15715/87461233-20ae6b00-c5dc-11ea-95b0-0e4dc6f0e397.png">
<img width="260" alt="Screen Shot 2020-07-14 at 2 12 55 PM" src="https://user-images.githubusercontent.com/15715/87461239-2310c500-c5dc-11ea-9e5f-220dd296bf3d.png">

**Comment by gavinnorman** [comment]
I don't know anything about what's possible in Roll20, but resolving an attack roll with the standard attack matrix should just be a 2d array lookup. (The character's THAC0 indicates the row, the attack roll indicates the column.)

If this isn't possible, it's probably worth indicating on the sheet somehow that the support for attack rolls only works with THAC0 / AAC, not with the default method (the attack matrix).

**Comment by gavinnorman** [comment]
By the way, note that using THAC0 / AAC to resolve attack rolls can give slightly different results compared to using the attack matrix. That's why THAC0 and AAC are both optional rules in OSE -- they're not completely 1:1 with the traditional matrix approach.

**Comment by Dextolen** [comment]
Just create a place for the user to input his to hits by AC , we can look at our own table and remember to change it as we level

**Comment by wesbaker** [comment]
> Just create a place for the user to input his to hits by AC , we can look at our own table and remember to change it as we level

Do you mean your character's THAC0? Because that exists on the Roll20 sheet and is changed automatically based on class and level. If it's just a matter of displaying that with each roll, that's easy enough.

**Comment by wesbaker** [comment]
Another option is I can show an attack matrix on the character sheet (and maybe the roll template).

**Comment by gavinnorman** [comment]
Showing the attack matrix for the character's class and level on the character sheet would be a good option.

**Comment by wesbaker** [comment]
Alright, so here's the end result. First on the character sheet you'll have the matrix like this:

<img width="853" alt="Screen Shot 2020-07-16 at 4 42 55 PM" src="https://user-images.githubusercontent.com/15715/87721225-1a5af300-c784-11ea-81bd-3483601c43d9.png">

Then, when you roll you'll also see a _tiny_ attack value matrix as well (though it will not appear for natural 1s or natural 20s):

<img width="260" alt="Screen Shot 2020-07-16 at 4 40 27 PM" src="https://user-images.githubusercontent.com/15715/87721268-2ba3ff80-c784-11ea-861c-28fdacebf8a4.png">

**Comment by Lodikai** [comment]
![image](https://user-images.githubusercontent.com/90922014/133817219-d9876ca6-1f96-4b73-8481-08fffe751e95.png)

DAC is throwing an extras line out it seems

**Comment by wesbaker** [comment]
> DAC is throwing an extras line out it seems

I'm tracking that in #75 and I just pushed up a fix for it that should hopefully take care of that.
