### ISSUE TITLE
Make roll buttons compatible for Macro Quick Bar

### ISSUE THREAD

**Issue by FrederickMuench** [wesbaker/roll20-character-sheets#34]
Roll20 supports the possibility to drag and drop roll buttons into the Macro Quick Bar, so that you don't have to open the sheet to make a roll ([see documentation](https://wiki.roll20.net/Macro_Quick_Bar)).

Maybe I am wrong, but i could swear that it worked in the past (on the old sheet).

**Comment by wesbaker** [comment]
There's not a ton of documentation on this. It seems like it either works or it doesn't. I'll try it out though.

**Comment by wesbaker** [comment]
@FrederickMuench aha, figured it out. It works on _most_ of the buttons and the ones where it doesn't is because I didn't add a `name` attribute to the button. Can you think of specific cases where it doesn't work (besides weapons, I already have that one fixed)?

**Comment by FrederickMuench** [comment]
@wesbaker weird, i can't move any button to the macro bar. Maybe it's a bug only i have.

**Comment by FrederickMuench** [comment]
@wesbaker my bad, they all work except for the attack button. (The drag & drop to the macro bar works only if the character sheet is not opened as a seperate window)
