### ISSUE TITLE
Movement rate is static?

### ISSUE THREAD

**Issue by frankie-break-bone** [wesbaker/roll20-character-sheets#35]
Apologies if this is my failure to understand or see something - the move rates seem to be fixed at 40, 120, 24. I'm not sure if they're tied to another editable field somewhere (I tested encumbrance - no change reflected), but being able to customize them at will would be ideal (As many things can affect move rates round to round).

Also sorry if I'm bad at GitHub and overlooked an existing open or closed issue :-D

**Comment by wesbaker** [comment]
@frankie-break-bone They aren't static, it's just that the overland and encounter movement rates are derived from the exploration movement rate. You only need to change the exploration movement rate.

![movement-rates](https://user-images.githubusercontent.com/15715/87686463-84f33b00-c752-11ea-8fc3-e18e68649015.gif)
