### ISSUE TITLE
Recommendation #2: A roll for initiative button and a modifier box.  

### ISSUE THREAD

**Issue by endeyequote** [wesbaker/roll20-character-sheets#39]
Also it would be great if initiative had a roll button as well as a box to input bonuses or penalties to account for custom rules and classes. 

Cheers!

**Comment by wesbaker** [comment]
Should be easy enough to turn the Init field into a button, so I don't even need to add anything. Digging around I _also_ see that monsters sometimes (rarely) have a modifier to their initiative as well, so I'll add that too.

**Comment by endeyequote** [comment]
That's great. Thanks!
