### ISSUE TITLE
Str/Dex modifiers have stopped applying to rolls

### ISSUE THREAD

**Issue by frankie-break-bone** [wesbaker/roll20-character-sheets#40]
I know Str and Dex mods were applying to melee, ranged, and initiative rolls about 48 hours ago, but they seem to have stopped. Dex still auto-adjusts AC though. 

Just an FYI, you might be under the hood as I type this :)

**Comment by wesbaker** [comment]
Hmm, they seemed to be working the last I looked, but I'll double check.

**Comment by wesbaker** [comment]
Ooh, this may be due to changing from ability and type to just type. Try changing the type of attack to the other option, then do it again selecting the correct attack type.

**Comment by frankie-break-bone** [comment]
Nice, works now - when I opened the issue I tried switching back and forth between melee and ranged with two different characters (one with high Str, one high Dex) and it was just rolling straight.

A+
