### ISSUE TITLE
Some bonuses don't apply?

### ISSUE THREAD

**Issue by frankie-break-bone** [wesbaker/roll20-character-sheets#47]
The new changes look great, fantastic work Wes! Found these, revisiting:

**Issue:**
Dex bonuses seem to apply automatically to attack rolls (yay!) but Strength does not 

Tested: Character with 17str (+2) melee roll, die roll of 12 registers as 12, not 14.

Current workaround: Using +attack field

**Issue:**
Halfling class does not receive +1 to missile (am currently adding manually with +Attack), or +1 to Initiative (which might be by design, as it is optional)

Tested: Halfling with 17 dex (+2) rolls 12 on ranged attack, registers as 14, not 15. 
Tested: Halfling initiative roll is straight d6.

Current workaround: Player is using the modal popup to add +1 on ranged and thrown weapons

**Issue:**
Initiative bonus modifier does not apply to roll
I assume this was to answer the optional nature of initiative bonuses? But, doesn't quite work

Tested: Added +1 bonus to initiative field, roll of 4 goes to turn counter as 4, not 5.

**Issue:**
Dexterity bonus does not affect initiative roll
Again, this might be by design, as init systems are DM's fiat - if so, disregard, see ^ above :)

**Comment by wesbaker** [comment]
> Dex bonuses seem to apply automatically to attack rolls (yay!) but Strength does not

There's a weird bug here. Try changing your attribute back and forth between Strength and Dexterity to see if that fixes it.



> Halfling class does not receive +1 to missile (am currently adding manually with +Attack), or +1 to Initiative (which might be by design, as it is optional)

That's less a bug and just something I never implemented. I'll write up a ticket for it.



> Initiative bonus modifier does not apply to roll
> I assume this was to answer the optional nature of initiative bonuses? But, doesn't quite work

> Dexterity bonus does not affect initiative roll

Go to settings and enable Individual Initiative:

<img width="861" alt="Screen Shot 2020-08-07 at 11 45 06 AM" src="https://user-images.githubusercontent.com/15715/89663374-79071e80-d8a3-11ea-923d-f087d2cef1dd.png">

**Comment by wesbaker** [comment]
Closing this in favor of #48 and #49
