### ISSUE TITLE
When rolling a saving throw prompt for the Wisdom modifier

### ISSUE THREAD

**Issue by shoshitsuten** [wesbaker/roll20-character-sheets#53]
It seems the WIS modifier isn't added to saving throws:
![image](https://user-images.githubusercontent.com/72185845/94773467-3426d200-0392-11eb-8a30-dcb07bd4df89.png)
(According to the sheet, it should've had a +3 there)

I'd also like to suggest a field where a universal modifier could be added, for things like the dwarf racial bonus, spells, etc.

**Comment by wesbaker** [comment]
[The wisdom modifier doesn't always apply](https://oldschoolessentials.necroticgnome.com/srd/index.php/Ability_Scores#Wisdom_.28WIS.29):

> Magic saves: Is applied to saving throws (see Saving Throws) versus magical effects. This does not normally include saves against breath attacks, but may apply to any other saving throw category.

As for the other modifier, it does prompt you for a modifier every time you roll a saving throw. You could add a note below or in skills for something specific.

**Comment by wesbaker** [comment]
I had a thought. I could add a question when you roll a saving throw that asks if the Wisdom modifier applies. By default it's a no, but you could select Yes from the drop down and it would be applied. How does that sound?

**Comment by shoshitsuten** [comment]
That would be good!

I don't know how hard it'd be to implement, but something like the global fields in the 5e sheet by roll20 would be even better.
You can turn them on like this:
![image](https://user-images.githubusercontent.com/72185845/96493966-11af0880-121c-11eb-8f2f-e26f1b2a6420.png)
Then you can global modifiers as flat bonuses or rolls:
![image](https://user-images.githubusercontent.com/72185845/96494131-4d49d280-121c-11eb-84d7-5214ddc0e375.png)
![image](https://user-images.githubusercontent.com/72185845/96494108-4622c480-121c-11eb-9d8b-0eefa957080e.png)

They're just checkboxes you can turn off if they no longer apply, but sometimes it's much more pratical to keep them on and just mentally ignore the bonus than turn them on/off. 

OSE is different, of course, but something like that would be useful for the WIS modifier and modifiers from spells, and even more useful with the Advanced rules, which have racial bonuses.
