### ISSUE TITLE
Dex Modifier

### ISSUE THREAD

**Issue by DoctorDuckButter** [wesbaker/roll20-character-sheets#54]
I am using the OSE sheet and for some reason when using descending AC, the Dex bonus is inverted now. Lower dex is helping, higher is hurting.

**Comment by DoctorDuckButter** [comment]
I actually found out the answer. When I created a new character, though I have it set to default to DAC, it made her come up as AAC. I changed it and everything is fine.

**Comment by wesbaker** [comment]
@DoctorDuckButter sounds like there is still a bug. I'll have to tinker around with defaults and how it handles that. This bit me before with weapons/attacks and the attribute to modify them by.

**Comment by DoctorDuckButter** [comment]
So I checked the settings, the sheet in Roll20 was set to AAC. I know this isn't correct because I made about 30 characters before this one and it was set for DAC and they still are DAC. I don't know why it flipped in the system suddenly?

**Comment by wesbaker** [comment]
@DoctorDuckButter that's odd. I'm pushing up a fix soon that might take care of it in the future.
