### ISSUE TITLE
Roll Attack Button Missing from Monster Character Sheet's Attacks Section

### ISSUE THREAD

**Issue by hemogoblinoid** [wesbaker/roll20-character-sheets#55]
When attempting to add an attack to a monster sheet, the roll attack button is missing and throwing the other input fields off by one position.

![image](https://user-images.githubusercontent.com/38544696/101229278-0cd7d400-3665-11eb-8045-8aa9fa7fee55.png)

**Comment by wesbaker** [comment]
@hemogoblinoid I think I have it fixed, I just pushed up a fix that should merge next week. For now, try going to settings and toggling between the different armor types (DAC -> AAC -> DAC or vice versa).
