### ISSUE TITLE
Allow custom amount of dice in damage roll

### ISSUE THREAD

**Issue by angorianka** [wesbaker/roll20-character-sheets#56]
Hi Wes!

I was just wondering if it's possible to change damage dice input in some way, where more than a single die can be rolled per attack. As an example, in our group we use rudimentary firearms from an addon ruleset: a blunderbuss deals 3d4 damage.

**Comment by wesbaker** [comment]
That’s reasonable and should be a pretty seamless change. Let my try it out tomorrow to see how it affects existing characters.

**Comment by wesbaker** [comment]
Yep, easy enough change and seamless on the update. It should go up next Monday or Tuesday.

<img width="858" alt="Screen Shot 2020-12-20 at 10 27 58 AM" src="https://user-images.githubusercontent.com/15715/102717098-1e002200-42ae-11eb-9d1f-083abb761397.png">

<img width="275" alt="Screen Shot 2020-12-20 at 10 28 09 AM" src="https://user-images.githubusercontent.com/15715/102717099-1fc9e580-42ae-11eb-997a-83da0f86841e.png">
