### ISSUE TITLE
Add Ability Score Modifier fields to Ability Scores

### ISSUE THREAD

**Issue by MarshallStaxx** [wesbaker/roll20-character-sheets#57]
Hello. I love the OSE Roll20 sheets, great work. 

I'd like to see separate fields for modifiers in the Ability Scores sections.

For example:

STR 12 (0)
INT 17 (+2)
WIS 8 (-1)
DEX 10 (0)
CON 15 (+1)
CHA 18 (+3)

Many of my players are new to OSE / D&D and don't have these modifier ranges memorised, causing confusion and delay when I ask them to add their Ability Score modifier to a certain roll.

Cheers,

Paul.

**Comment by wesbaker** [comment]
Hey Paul, this would be easily done, but most of these modifiers are automatically applied (or shown) where applicable. Is it just a matter of giving your players an idea of how they translate into modifiers or are you using them for something?

**Comment by MarshallStaxx** [comment]
Hey Wes, thanks for getting back to me.

In my OSE game, I often use '2d6 + ability score modifier' rolls for checks, rather than '1d20 roll under ability score'. If the modifier was present on the character sheet, it would allow the newer player to make that 2d6 + ability score modifier roll themselves without asking my input.

For example, in my Stonehell game recently, a Dwarf PC was trying to sweet-talk a Kobold work-crew leader. I asked him to roll 2d6 + CHA modifier. He didn't quite understand, rolled boxcars, added his CHA of 8, and told me that he got a 20!

Cheers,

Paul.

**Comment by MarshallStaxx** [comment]
FYI I'm not asking for you to program a 2d6 + ability score modifier function built-into the character sheet itself. Just having the modifier displayed would allow players to manually roll 2d6 + modifier.

**Comment by wesbaker** [comment]
No worries, I understand what you’re asking for 😄 and it makes sense. I’ll add it shortly. Shouldn’t be too tough.

**Comment by MarshallStaxx** [comment]
Thank you, Wes. Have a nice day.
