### ISSUE TITLE
Problem with Old-school Essentials character sheet (armour class)

### ISSUE THREAD

**Issue by matzede83** [wesbaker/roll20-character-sheets#59]
Hi,

I've started creating a character with the old-school essential character sheet. It looks pretty good but when it comes to armour classes it seems to calculate bonuses the wrong way.

If a hero gets DEX 13 there should be a bonus of +1 (which lowers the AC acc. to the Core Rules). However, the character sheets seems to add the bonus to the AC which results in worse hit saving.

Furthermore if the character has no armour the AC should be 9 acc. to the core rules but the sheet shows 10.

Can you help? Thanks.

**Comment by wesbaker** [comment]
Sure. It sounds like you're looking for DAC, but my sheet uses AAC by default. Go to the settings tab and change it over to Descending and it should work how you'd expect.

**Comment by matzede83** [comment]
oh man! That's what I was looking for.
Thanks!

**Comment by wesbaker** [comment]
One other thing, when you're setting up a game, there's a setting that defaults the AC type and you can set that to DAC so all new characters are automatically set to that as well. Go to Game Settings and scroll down:

![image](https://user-images.githubusercontent.com/15715/105633142-f6f4bd00-5e24-11eb-959e-04b3b372e110.jpeg)
