### ISSUE TITLE
the AAC sheet seems to mix up characters and monsters

### ISSUE THREAD

**Issue by Pusikas** [wesbaker/roll20-character-sheets#6]
Sorry, posted this initially in the wrong repo:
https://github.com/Roll20/roll20-character-sheets/issues/6530

Basically, it looks to me like the weapons from the character tab and the monster tab are linked. When I enter weapons on the character tab, they appear on the monster tab as well. I can edit them there, too, and the changes are reflected on the character tab.

Pressing the roll button next to a weapon on the character tab executes the macro code from the monster tab. This way, attribute bonuses, +attack and +damage entered on the character tab are being ignored.

You may want to check out the linked issue, I posted some nice pictures and the macro code there. :)

**Comment by Pusikas** [comment]
Also (probably unrelated), why is there an invisible field for the weapon description that is empty by default? I'd love a working version of that one.

**Comment by wesbaker** [comment]
Both of those were intentional. 

I kept the monster and character attacks linked in case you started on one and realized you wanted the other. I expected that most people wouldn’t use one sheet for both a character **and** a monster.

The description for the weapon is invisible on the character sheet because there wasn’t much room left and I didn’t expect to use it much. I could make it the second row, but I feel like it wouldn’t be used that often.

**Comment by wesbaker** [comment]
It does look like a bug that it’s using the monster stats for the character sheet, I’ll take a look.

**Comment by wesbaker** [comment]
> Pressing the roll button next to a weapon on the character tab executes the macro code from the monster tab. This way, attribute bonuses, +attack and +damage entered on the character tab are being ignored.

So digging more into the bug, here's what I believe happens:

1. You go to the monster tab and create an attack, when you do that it creates the button as well and saves the value of the macro to the roll
2. You then change tabs to the character sheet and the attack is there (this is intentional), but the macro for the roll is saved as well (this is unintentional)

If I can divorce the value of the button from the saved state of the attack/weapon, then I'll likely go that route and keep them both linked.

**Comment by Pusikas** [comment]
> 
> Both of those were intentional.
> 
> I kept the monster and character attacks linked in case you started on one and realized you wanted the other. I expected that most people wouldn’t use one sheet for both a character **and** a monster.
> 
Okay. But then why did you not link the names as well? I just noticed that I have to put a monster's name in the character tab, or otherwise it will not show in the Journal or on a token. The name on the monster tab does not seem appear anywhere.

**Comment by wesbaker** [comment]
> But then why did you not link the names as well? I just noticed that I have to put a monster's name in the character tab, or otherwise it will not show in the Journal or on a token. The name on the monster tab does not seem appear anywhere.

That was unintentional. I'll fix that.

**Comment by Pusikas** [comment]
> The description for the weapon is invisible on the character sheet because there wasn’t much room left and I didn’t expect to use it much. I could make it the second row, but I feel like it wouldn’t be used that often.

Yes, I can see that there is not that much room for it. I have seen some other sheets (for other systems) hide detailled stuff behind a cogwheel. No idea if that is something you may want to implement.

I would use the description for specials and additional information. In a character's ranged weapon I'd put the ranges of said weapon. In the description of a monster's weapon I'd put things like "Poison: Causes death (save vs poison).".

That's why I'd love to see the description with the roll. Actually, the monster's roll macro code looks like the description should get displayed. Does not show for me, tho.

**Comment by Pusikas** [comment]
If you'd rather have me open seperate issues for each of these, just say so.

**Comment by Pusikas** [comment]
Also, I am currently on the "Plus" level on Roll20. Would I be able to test your changes on the "Pro" level of Roll20? Been thinking about that, anyway. (yes, sorry, that doesn't have anything to do with this issue)

**Comment by wesbaker** [comment]
> Yes, I can see that there is not that much room for it. I have seen some other sheets (for other systems) hide detailled stuff behind a cogwheel. No idea if that is something you may want to implement.

That's a good idea. I'll look into it.

> If you'd rather have me open seperate issues for each of these, just say so.

No worries, this is fine.

> Also, I am currently on the "Plus" level on Roll20. Would I be able to test your changes on the "Pro" level of Roll20?

Yes, you can create a custom sheet sandbox and upload files as you work on them.

**Comment by wesbaker** [comment]
Excuse the testing nonsense, but here's what it'll look like

<img width="848" alt="Screen Shot 2020-05-20 at 1 13 32 PM" src="https://user-images.githubusercontent.com/15715/82476258-c2618200-9a9b-11ea-9d35-679efbaffca0.png">

**Comment by Pusikas** [comment]
Nice! Cogwheel directly next to the roll button may not be perfect, but no matter where you put it, someone will complain. 😄

**Comment by wesbaker** [comment]
I was unsure where to put it. Any suggestions? Moving it is easy.

**Comment by Pusikas** [comment]
Maybe just to the far right. Weight of a weapon does not change that often, so accidental clicks should be rare.

**Comment by wesbaker** [comment]
Done, now we wait for Roll20 to merge it, usually on Mondays, and then it goes live on Tuesdays or so.

**Comment by Pusikas** [comment]
That would be extremely nice! I got a game on Tuesday. 😄
