### ISSUE TITLE
Saving Throw Inconsistency?

### ISSUE THREAD

**Issue by dittomikey** [wesbaker/roll20-character-sheets#66]
All of the saves but Death, Poison add the optional modifier to the die roll.  The Death, Poison save adds the optional modifier to the the target- effectively making this save use modifiers in the exact opposite way that all of the other do.

Bug?

**Comment by wesbaker** [comment]
Yep, totally a bug. I'll get on that now.

**Comment by wesbaker** [comment]
@dittomikey this was merged today (so fast!) and should be available soonish. I've seen it take 24 hours, but there's a chance it's up sooner.
