### ISSUE TITLE
Modifiers fields require a minimum value of 0

### ISSUE THREAD

**Issue by tiapfy** [wesbaker/roll20-character-sheets#67]
In my character sheet, when I set any ability score to 8 or less, the modifier is set to a negative value, as it should be. The problem manifests when I try to add something to my gear and an error appears on the modifier field, interrupting the procedure. The error shown is the default HTML error:
![image](https://user-images.githubusercontent.com/31632081/107157659-8782df80-6985-11eb-999c-e905edb968ed.png)
If i try to inspect the field I can see that the input element requires a value of 0 or more:
![image](https://user-images.githubusercontent.com/31632081/107157712-fc561980-6985-11eb-81d6-0aaef7bf068e.png)

**Comment by wesbaker** [comment]
Whoops, total copy pasta on my part. I've pushed up a fix and it should get merged shortly.

**Comment by tiapfy** [comment]
Thank you for the quick response
