### ISSUE TITLE
leaving the "Effect Roll" empty causes a Syntax Error

### ISSUE THREAD

**Issue by Pusikas** [wesbaker/roll20-character-sheets#7]
Some spells don't have an effect roll. It would be nice if the player could press the roll button, anyway, to indicate that they're casting the spell und post the description. Currently, this yields an error message like this:
`SyntaxError: Expected "(", ".", "[", "abs(", "ceil(", "d", "floor(", "round(", "t", "{", [ |\t], [+|\-] or [0-9] but end of input found.`

**Comment by wesbaker** [comment]
I think the best thing I can do is have two buttons: one would roll and one would display. Without having the API available you can’t put logic into the things that display in the chat. That’s easy enough to do though.

**Comment by wesbaker** [comment]
Alright, I have a solution I'm happy with. The buttons show or hide depending on the value in "Effect Roll"

<img width="842" alt="Screen Shot 2020-05-24 at 2 12 11 PM" src="https://user-images.githubusercontent.com/15715/82761460-af66ee80-9dc8-11ea-8fb3-de657cdb7634.png">

<img width="263" alt="Screen Shot 2020-05-24 at 2 12 28 PM" src="https://user-images.githubusercontent.com/15715/82761462-b130b200-9dc8-11ea-8dc6-1eaa82c34f09.png">

**Comment by Pusikas** [comment]
I like it!

**Comment by wesbaker** [comment]
Should go out Tuesday 🤞
