### ISSUE TITLE
Wrong translation for french OSE character sheet

### ISSUE THREAD

**Issue by BobbyWats0n** [wesbaker/roll20-character-sheets#71]
Greetings,

In the Old School Essential _french_ character sheet, there is a mistake/bug in one of the saving throws button (characters and monsters alike). The "_Breath attacks_" is wrong and displays "Paralysie ou pétrification", which is 'Paralysis or petrification', of course.

This is certainly more of a bug than a translation mistake, but it should be easy to fix, probably.

I am no translator, but just in case you have no translation yet and one else than the Internet to help you, the "Breath attacks" save button should probably be translated as " **Souffle** ". 
This is not a word-for-word translation of 'breath attacks' ("_Attaques de souffle_" does not suit very well, IMO), but it is the best we can have, as the french D&D books I own translate dragon breaths (and others) as "**souffle**" (the 'attaque' goes without saying). But you do you, again, not a translator.

The rest of the character sheet's translation, by the way, is great! Very very cool tool, especially when OSE does not have a french translation (officially at least).

Best regards,
BobbyWats0n

**Comment by wesbaker** [comment]
Hey there! I don't submit or control translations, they all go through CrowdIn:

> Please email Cassie at [cassie@roll20.net](mailto:cassie@roll20.net) and she will get you an invite to our Crowdin within 48 hours. Be sure to include the languages you would like to translate, Please use that for future translation updates! Thanks for all you do!

Contact them to get into their translation system and submit the fixes.

**Comment by BobbyWats0n** [comment]
Hello,

I tried to e-mail Cassie at ***@***.*** but the email returned
unfortunately...

**Comment by wesbaker** [comment]
Hmm, the instructions may have changed since then, take a look here: https://help.roll20.net/hc/en-us/articles/360058423993-How-to-Become-a-Translation-Volunteer
