### ISSUE TITLE
OSE Slot based

### ISSUE THREAD

**Issue by funkrockwarlock** [wesbaker/roll20-character-sheets#76]
Hi I am currently using your OSE character sheet and loving it. It's really great and I appreciate the work you've done and it's amazing that it's available for free. I like using the slot based encumbrance rules (link below) and was wondering if you planned to make that an option, similar  to what you did for ascending or descending AC. I would be happy to become a patron for whatever we can agree is a fair price as I believe in paying for people's work but I'm not sure if this is a project you've abandoned. Currently we're using google docs to track but it's not as user-friendly for some of my players, and something like this would make it much easier.

https://necroticgnome.com/blogs/news/item-based-encumbrance-play-test

Is this a project you are considering continuing? I know nothing about coding is it too difficult? What would be a fair patronage amount? I would like to pay as fairly as possible for your time but am working with a limited budget myself. We can message privately  the details before you start anything because I don't want to waste your time. 

Thanks for taking a minute to read this. I know nothing of Github, I just followed the link from patreon and made an account so I'll try to keep an eye on notifications. 
Take care-
FRW

**Comment by wesbaker** [comment]
> Is this a project you are considering continuing?

It's neat and I think it's doable with repeating sections, but I don't work on these Roll20 sheets these days because I play exclusively in Foundry. If you wanted to tinker around with it, it's not too tough, but almost necessitates the top paid subscription in Roll20 (one small reason why I haven't been updating this sheet much).
